### ISSUE TITLE
openvpn.heat - Security groups are not applied automatically

### ISSUE THREAD

**Issue by bingoarunprasath** [cloudwatt/openstack-heat-templates#2]
The security groups are not applied automatically, we have to manually add it after the heat template is completed. The rest of the script is working fine.

**Comment by bingoarunprasath** [comment]
Proposed a fix  - https://github.com/cloudwatt/openstack-heat-templates/pull/3

**Comment by ygbourhis** [comment]
Thanks a lot for the patch.
